-- Show columns
SELECT * FROM BRIGHT_DEALERSHIP.AUTO_MOBILE.DATASET;

-- Cleaned vehicle sales dataset with deduplication, null handling, and day classification
SELECT DISTINCT
  -- Text columns
  CASE WHEN MAKE IS NULL THEN 'None' ELSE MAKE END AS MAKE,
  CASE WHEN MODEL IS NULL THEN 'None' ELSE MODEL END AS MODEL,
  CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END AS TRIM,
  CASE WHEN BODY IS NULL THEN 'None' ELSE BODY END AS BODY,
  CASE WHEN TRANSMISSION IS NULL THEN 'None' ELSE TRANSMISSION END AS TRANSMISSION,
  CASE WHEN VIN IS NULL THEN 'None' ELSE VIN END AS VIN,
  CASE WHEN STATE IS NULL THEN 'None' ELSE STATE END AS STATE,
  CASE WHEN COLOR IS NULL THEN 'None' ELSE COLOR END AS COLOR,
  CASE WHEN INTERIOR IS NULL THEN 'None' ELSE INTERIOR END AS INTERIOR,
  CASE WHEN SELLER IS NULL THEN 'None' ELSE SELLER END AS SELLER,

  -- Numeric columns
  CASE WHEN YEAR IS NULL THEN 0 ELSE YEAR END AS YEAR,
  CASE WHEN CONDITION IS NULL THEN 0 ELSE CONDITION END AS CONDITION,
  CASE WHEN MMR IS NULL THEN 0 ELSE MMR END AS MMR,

  -- Cleaned numeric price
  CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC) AS selling_price_numeric,

  -- Sales metrics
  COUNT(*) AS units_sold,
  SUM(CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC)) AS total_revenue,

  -- Profit margin calculation
  ROUND(
    (CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC) - 
     CASE WHEN MMR IS NULL THEN 0 ELSE MMR END)
    / NULLIF(CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC), 0) * 100,
    2
  ) AS profit_margin_percent,

  -- Performance tier classification
  CASE
    WHEN (CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC) - 
          CASE WHEN MMR IS NULL THEN 0 ELSE MMR END)
         / NULLIF(CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC), 0) >= 0.25
      THEN 'High Margin'
    WHEN (CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC) - 
          CASE WHEN MMR IS NULL THEN 0 ELSE MMR END)
         / NULLIF(CAST(REPLACE(CASE WHEN SELLINGPRICE IS NULL THEN '0' ELSE SELLINGPRICE END, ',', '') AS NUMERIC), 0) BETWEEN 0.10 AND 0.249
      THEN 'Medium Margin'
    ELSE 'Low Margin'
  END AS performance_tier,

  -- Fuel type inference
  CASE
    WHEN LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%hybrid%' THEN 'Hybrid'
    WHEN LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%ev%' 
       OR LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%electric%' THEN 'Electric'
    WHEN LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%diesel%' THEN 'Diesel'
    WHEN LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%gas%' 
       OR LOWER(CASE WHEN TRIM IS NULL THEN 'None' ELSE TRIM END) LIKE '%petrol%' THEN 'Petrol'
    ELSE 'Unknown'
  END AS inferred_fuel_type,

  -- Timestamp formatting
  TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS') AS sale_timestamp,
  CAST(TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS') AS DATE) AS sale_date,
  TO_CHAR(TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS'), 'HH24:MI:SS') AS sale_time,
  DAYNAME(TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) AS day_name,
  EXTRACT(HOUR FROM TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) AS hour_of_the_day,

  -- Fixed Case for day classification (numeric hour ranges)
  CASE 
    WHEN EXTRACT(HOUR FROM TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) BETWEEN 6 AND 11 THEN 'Morning'
    WHEN EXTRACT(HOUR FROM TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) BETWEEN 12 AND 16 THEN 'Afternoon'
    WHEN EXTRACT(HOUR FROM TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) BETWEEN 17 AND 20 THEN 'Evening'
    ELSE 'Night'
  END AS Dayclassification,

  -- Time period grouping
  MONTHNAME(TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) AS month_name,
  QUARTER(TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) AS quarter,
  EXTRACT(YEAR FROM TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS')) AS sale_year

FROM BRIGHT_DEALERSHIP.AUTO_MOBILE.DATASET
WHERE TRY_TO_TIMESTAMP(saledate, 'Dy Mon DD YYYY HH24:MI:SS') IS NOT NULL

GROUP BY
  YEAR, MAKE, MODEL, TRIM, BODY, TRANSMISSION, VIN, STATE, CONDITION, COLOR, INTERIOR, SELLER, MMR,
  SELLINGPRICE, SALEDATE;

